apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../application/database  

#namespace: fbca9a-dev


  #namespace: example
  #behavior: replace
secretGenerator:
- name: pims-database
  env:
  - database.env.txt
  type: Opaque
images:
- name: image-registry.apps.silver.devops.gov.bc.ca/5b7aa5-tools/pims-database
  newName: image-registry.apps.silver.devops.gov.bc.ca/5b7aa5-tools/pims-database
  newTag: latest #CI build_number
