apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-deploy-dev
  namespace: 5b7aa5-tools
spec:
  params:
    - default: 'https://github.com/sookeke/quarkus-and-github-actions.git'
      description: The application git repository
      name: APP_SOURCE_GIT
      type: string
    - default: master
      description: The application git revision
      name: APP_SOURCE_REVISION
      type: string
    - default: 'https://github.com/bcgov-c/ministry-gitops-jag.git'
      description: The application configuration git repository
      name: APP_CONFIG_GIT
      type: string
    - default: 'https://github.com/sookeke/spring-petclinic-gatling'
      description: The application test cases git repository
      name: APP_TESTS_GIT
      type: string
    - default: quarkus-demo
      description: The application image to build
      name: APP_IMAGE
      type: string
    - default: latest
      description: The application image tag to build
      name: APP_IMAGE_TAG
      type: string
  tasks:
    - name: source-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: depth
          value: '0'
        - name: subdirectory
          value: Quarkus-k8s
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: config-clone
      params:
        - name: url
          value: $(params.APP_CONFIG_GIT)
        - name: subdirectory
          value: Quarkus-k8s
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: main
        - name: sslVerify
          value: 'true'
        - name: depth
          value: '0'
      runAfter:
        - source-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: deploy-dev
      params:
        - name: DEPLOYMENT_NAME
          value: quarkus-demo
        - name: CURRENT_IMAGE
          value: quarkus-demo
        - name: NEW_IMAGE_NAME
          value: $(params.APP_IMAGE)
        - name: NEW_IMAGE_TAG
          value: $(params.APP_IMAGE_TAG)
        - name: NEW_IMAGE_DIGEST
          value: from CI
        - name: NAMESPACE
          value: 5b7aa5-dev
        - name: KUSTOMIZE_OVERLAY_DIR
          value: Quarkus-k8s/environment/dev
      runAfter:
        - config-clone
      taskRef:
        kind: Task
        name: deploy-app
      workspaces:
        - name: source
          subPath: Quarkus-k8s
          workspace: workspace
  workspaces:
    - name: workspace
    - name: quarkus-settings
