apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pims-api-deploy-dev
  namespace: 5b7aa5-tools
spec:
  params:
    - default: 'https://github.com/bcgov/ag-pssg-sdlc.git'
      description: The application git repository
      name: APP_SOURCE_GIT
      type: string
    - default: main
      description: The application git revision
      name: APP_SOURCE_REVISION
      type: string
    - default: quarkus-demo
      description: The application image to build
      name: APP_IMAGE
      type: string
    - default: latest
      description: The application image tag to build
      name: APP_IMAGE_TAG
      type: string
    - default: Server=pims-database,1433;User ID=admin;Database=pims
      description: The application image tag to build
      name: CONNECTION_STRINGS_PIMS
      type: string
    - default: https://sso-dev-5b7aa5-dev.apps.silver.devops.gov.bc.ca/auth/realms/PIMS
      description: The application image tag to build
      name: KEYCLOAK_AUTHORITY
      type: string      
     - default: https://sso-dev-5b7aa5-dev.apps.silver.devops.gov
      description: The application image tag to build
      name: KEYCLOAK_ADMIN_AUTHORITY
      type: string     
    - default: ee7d21ac-84a4-477a-950c-4c72d019fd95 
      description: The application image tag to build
      name: KEYCLOAK_SERVICE_ACCOUNT_SECRET
      type: string      
     - default: WSpmqqNJMqo__1Ab!
      description: The application image tag to build
      name: DB_PASSWORD
      type: string
     - default: admin
      description: The application image tag to build
      name: DB_USER
      type: string
     - default: v6lA2_MAgYNtu7R9H6ClN_1aB!
      description: The application image tag to build
      name: MSSQL_SA_PASSWORD
      type: string      
      
      
      
  tasks:
    - name: source-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: depth
          value: '0'
        - name: subdirectory
          value: k8s
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: deploy-pims-api-dev
      params:
        - name: DEPLOYMENT_NAME
          value: pims-database
        - name: IMAGE_TAG
          value: latest
        - name: CONNECTION_STRINGS_PIMS
          value: $(params.CONNECTION_STRINGS_PIMS)
        - name: KEYCLOAK_AUTHORITY
          value: $(params.KEYCLOAK_AUTHORITY)
        - name: KEYCLOAK_ADMIN_AUTHORITY
          value: $(params.KEYCLOAK_ADMIN_AUTHORITY)
        - name: KEYCLOAK_SERVICE_ACCOUNT_SECRET
          value: $(params.KEYCLOAK_SERVICE_ACCOUNT_SECRET)          
        - name: DB_PASSWORD
          value: $(params.DB_PASSWORD)
        - name: DB_USER
          value: $(params.DB_USER)
        - name: MSSQL_SA_PASSWORD
          value: $(params.MSSQL_SA_PASSWORD)
        - name: NAMESPACE
          value: 5b7aa5-dev
        - name: KUSTOMIZE_BACKEND_DIR
          value: k8s/environments/dev/backend
        - name: KUSTOMIZE_FRONTEND_DIR
          value: k8s/environments/dev/frontend
        - name: KUSTOMIZE_DATABASE_DIR
          value: k8s/environments/dev/database
      runAfter:
        - source-clone
      taskRef:
        kind: Task
        name: deploy-pims-api
      workspaces:
        - name: source
          subPath: k8s
          workspace: workspace
  workspaces:
    - name: workspace
    - name: pims-settings
