apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-quarkus-deploy-dev
  namespace: 5b7aa5-tools
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitshortsha
    description: The short commit sha
    default: master
  - name: gitbranchname
    description: The branch name
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations: {}
        generateName: quarkus-deploy-dev-
        labels:
          tekton.dev/pipeline: quarkus-deploy-dev
        namespace: 5b7aa5-tools
      spec:
        params:
          - name: APP_SOURCE_GIT
            value: 'https://github.com/sookeke/quarkus-and-github-actions.git'
          - name: APP_SOURCE_REVISION
            value: master
          - name: APP_CONFIG_GIT
            value: 'https://github.com/bcgov-c/ministry-gitops-jag.git'
          - name: APP_TESTS_GIT
            value: 'https://github.com/siamaksade/spring-petclinic-gatling'
          - name: APP_IMAGE
            value: quarkus-demo
          - name: APP_IMAGE_TAG
            value: latest
        pipelineRef:
          name: quarkus-deploy-dev
        resources: []
        status: null
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: source-pvc
          - name: quarkus-settings
            persistentVolumeClaim:
              claimName: source-pvc

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-quarkus-deploy-dev
  namespace: 5b7aa5-tools
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitshortsha
    value: $(body.short_sha)
  - name: gitbranchname
    value: $(body.branch_name)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: contenttype
    value: $(header.Content-Type)
---