apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
  namespace: 5b7aa5-tools
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook
      interceptors:
        - cel:
            overlays:
            - key: short_sha
              expression: "body.after.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
      bindings:
        - ref: git-triggerbinding
      template:
        ref: petclinic-trigger-template