apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: devsecops-qa
    server: https://kubernetes.default.svc
  project: spring-petclinic
  source:
    path: environments/stage
    repoURL: http://{{ r_gogs_route.resources[0].spec.host }}/gogs/spring-petclinic-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
