apiVersion: apps/v1
kind: Deployment
metadata:
  name: pims-api
spec:
  template:
    spec:
      containers:
      - name: pims-api
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
