apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-pims
  namespace: 5b7aa5-tools
spec:
  params:
    - description: The name of deployment
      name: DEPLOYMENT_NAME
      type: string
    - description: The name of deployment
      name: DEPLOYMENT_NAME_API
      type: string
    - description: The name of deployment
      name: DEPLOYMENT_NAME_APP
      type: string
    - description: The name of deployment
      name: IMAGE_TAG
      type: string
    - description: The name of deployment
      name: CONNECTION_STRINGS_PIMS
      type: string
    - description: The name of deployment
      name: DB_PASSWORD
      type: string
    - description: The name of deployment
      name: DB_USER
      type: string
    - description: The name of deployment
      name: MSSQL_SA_PASSWORD
      type: string
    - description: 'The current image repo/image:tag in the manifests for the deployment'
      name: KEYCLOAK_AUTHORITY
      type: string
    - description: The new image repo/image to be deployed
      name: KEYCLOAK_ADMIN_AUTHORITY
      type: string
    - default: ''
      description: The new image tag to be deployed
      name: KEYCLOAK_SERVICE_ACCOUNT_SECRET
      type: string
    - default: ''
      description: The digest of the new image to get deployed
      name: NEW_IMAGE_DIGEST
      type: string
    - description: The namespace for the deployment
      name: NAMESPACE
      type: string
    - description: >-
        The subdirectory in configs git repo for the kustomize overlay to be
        applied
      name: KUSTOMIZE_DATABASE_DIR
      type: string
    - description: >-
        The subdirectory in configs git repo for the kustomize overlay to be
        applied
      name: KUSTOMIZE_BACKEND_DIR
      type: string
    - description: >-
        The subdirectory in configs git repo for the kustomize overlay to be
        applied
      name: KUSTOMIZE_FRONTEND_DIR
      type: string
  steps:
    - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli'
      name: apply-database-manifests
      resources: {}
      script: >
        #find $(workspaces.source.path)

        echo \

        "DB_PASSWORD=$(params.DB_PASSWORD) 

        DB_USER=$(params.DB_USER)

        MSSQL_SA_PASSWORD=$(params.MSSQL_SA_PASSWORD)" >>
        $(workspaces.source.path)/$(params.KUSTOMIZE_DATABASE_DIR)/database.env.txt



        echo "########################"  

        echo "## kustomization.yaml ##"

        echo "########################"

        cat
        $(workspaces.source.path)/$(params.KUSTOMIZE_DATABASE_DIR)/kustomization.yaml


        cat
        $(workspaces.source.path)/$(params.KUSTOMIZE_DATABASE_DIR)/database.env.txt

        # Cancel all previous deployments

        OC_CANCEL_ALL_PREV_DEPLOY="oc -n $(params.NAMESPACE) rollout cancel
        dc/$(params.DEPLOYMENT_NAME) || true"

        echo "canceling previous deployments..." 

        #eval "${OC_CANCEL_ALL_PREV_DEPLOY}" 

        count=1 

        timeout=10

          # Check previous deployment statuses before moving onto new deploying
          while [ $count -le $timeout ]; do
            sleep 1
            PENDINGS="$(oc -n $(params.NAMESPACE)rollout history dc/$(params.DEPLOYMENT_NAME) | awk '{print $2}' | grep -c Pending || true)"
            RUNNINGS="$(oc -n $(params.NAMESPACE) rollout history dc/$(params.DEPLOYMENT_NAME) | awk '{print $2}' | grep -c Running || true)"
            if [ "${PENDINGS}" == 0 ] && [ "${RUNNINGS}" == 0 ]; then
              # No pending or running replica controllers so exit the while loop
              break 2
            fi
            count=$(( ${count} + 1 ))
          done
          if [ ${count} -gt ${timeout} ]; then
            echo "\n*** Reached the timeout for canceling previous deployments ***\n"
            exit 1
          fi

        ls -A $(workspaces.source.path)/$(params.KUSTOMIZE_DATABASE_DIR)/


        echo "######## DRY RUN #######"

        oc apply -k $(params.KUSTOMIZE_DATABASE_DIR) --dry-run=client -o yaml -n
        $(params.NAMESPACE)

        echo "########################"

        oc apply -k $(params.KUSTOMIZE_DATABASE_DIR) -n $(params.NAMESPACE)

        oc rollout status dc/$(params.DEPLOYMENT_NAME) --watch -n
        $(params.NAMESPACE)

        echo "Done deploying $(params.DEPLOYMENT_NAME)"


        #ROUTE=$(oc get route $(params.DEPLOYMENT_NAME) -n $(params.NAMESPACE)
        #--template='{{ .spec.host }}')

        #echo "http://${ROUTE}/
      workingDir: $(workspaces.source.path)
    - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli'
      name: apply-backend-manifest
      resources: {}
      script: >
        echo \

        "KEYCLOAK_SERVICE_ACCOUNT_SECRET=$(params.KEYCLOAK_SERVICE_ACCOUNT_SECRET)

        KEYCLOAK_SECRET=sample" >>
        $(workspaces.source.path)/$(params.KUSTOMIZE_BACKEND_DIR)/pims-api.env.txt



        echo "########################"  

        echo "## kustomization.yaml ##"

        echo "########################"

        cat
        $(workspaces.source.path)/$(params.KUSTOMIZE_BACKEND_DIR)/kustomization.yaml




        # Cancel all previous deployments

        OC_CANCEL_ALL_PREV_DEPLOY="oc -n $(params.NAMESPACE) rollout cancel
        dc/$(params.DEPLOYMENT_NAME_API) || true"

        echo "canceling previous deployments..." 

        #eval "${OC_CANCEL_ALL_PREV_DEPLOY}" 

        count=1 

        timeout=10

          # Check previous deployment statuses before moving onto new deploying
          while [ $count -le $timeout ]; do
            sleep 1
            PENDINGS="$(oc -n $(params.NAMESPACE)rollout history dc/$(params.DEPLOYMENT_NAME_API) | awk '{print $2}' | grep -c Pending || true)"
            RUNNINGS="$(oc -n $(params.NAMESPACE) rollout history dc/$(params.DEPLOYMENT_NAME_API) | awk '{print $2}' | grep -c Running || true)"
            if [ "${PENDINGS}" == 0 ] && [ "${RUNNINGS}" == 0 ]; then
              # No pending or running replica controllers so exit the while loop
              break 2
            fi
            count=$(( ${count} + 1 ))
          done
          if [ ${count} -gt ${timeout} ]; then
            echo "\n*** Reached the timeout for canceling previous deployments ***\n"
            exit 1
          fi

        ls -A $(workspaces.source.path)/$(params.KUSTOMIZE_BACKEND_DIR)/


        echo "######## DRY RUN #######"

        oc apply -k $(params.KUSTOMIZE_BACKEND_DIR) --dry-run=client -o yaml -n
        $(params.NAMESPACE)

        echo "########################"

        oc apply -k $(params.KUSTOMIZE_BACKEND_DIR) -n $(params.NAMESPACE)

        oc rollout status dc/$(params.DEPLOYMENT_NAME_API) --watch -n
        $(params.NAMESPACE)

        echo "Done deploying $(params.DEPLOYMENT_NAME_API)"
      workingDir: $(workspaces.source.path)
    - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli'
      name: apply-frontend-manifest
      resources: {}
      script: >

        echo "########################"  

        echo "## kustomization.yaml ##"

        echo "########################"

        cat
        $(workspaces.source.path)/$(params.KUSTOMIZE_FRONTEND_DIR)/kustomization.yaml


        # Cancel all previous deployments

        OC_CANCEL_ALL_PREV_DEPLOY="oc -n $(params.NAMESPACE) rollout cancel
        dc/$(params.DEPLOYMENT_NAME_API) || true"

        echo "canceling previous deployments..." 

        #eval "${OC_CANCEL_ALL_PREV_DEPLOY}" 

        count=1 

        timeout=10

          # Check previous deployment statuses before moving onto new deploying
          while [ $count -le $timeout ]; do
            sleep 1
            PENDINGS="$(oc -n $(params.NAMESPACE)rollout history dc/$(params.DEPLOYMENT_NAME_APP) | awk '{print $2}' | grep -c Pending || true)"
            RUNNINGS="$(oc -n $(params.NAMESPACE) rollout history dc/$(params.DEPLOYMENT_NAME_APP) | awk '{print $2}' | grep -c Running || true)"
            if [ "${PENDINGS}" == 0 ] && [ "${RUNNINGS}" == 0 ]; then
              # No pending or running replica controllers so exit the while loop
              break 2
            fi
            count=$(( ${count} + 1 ))
          done
          if [ ${count} -gt ${timeout} ]; then
            echo "\n*** Reached the timeout for canceling previous deployments ***\n"
            exit 1
          fi

        ls -A $(workspaces.source.path)/$(params.KUSTOMIZE_FRONTEND_DIR)/


        echo "######## DRY RUN #######"

        oc apply -k $(params.KUSTOMIZE_FRONTEND_DIR) --dry-run=client -o yaml -n
        $(params.NAMESPACE)

        echo "########################"

        oc apply -k $(params.KUSTOMIZE_FRONTEND_DIR) -n $(params.NAMESPACE)

        oc rollout status dc/$(params.DEPLOYMENT_NAME_APP) --watch -n
        $(params.NAMESPACE)

        echo "Done deploying $(params.DEPLOYMENT_NAME_APP)"
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
