name: Credentials Scan

# read-only repo token
# no access to secrets
on:
  pull_request:
    branches: [master, test, dev]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  credentials-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Display python version
        run: python -c "import sys; print(sys.version)"

      - name: Cache python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          key: ${{ runner.os }}-pip

      - name: Install requirements
        run: pip install trufflehog3 jtbl

      - name: Scan with trufflehog3
        id: scan
        run: trufflehog3 --no-history --config .github/.trufflehog3.yml --format json --output trufflehog_report.json

      - name: Trufflehog3 Scan and Parse Report
        if: always()
        uses: netlify/security-netlify-trufflehog3@v0.6.4
        with:
          trufflehog_report_file_path: 'trufflehog_report.json'
          suppression_file_path: '.github/suppressions-trufflehog3'
          ignore_paths_file_path: '.github/ignore-paths-trufflehog3'
          create_github_issue: 'true'
          secret_scan_gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo_name: ${{ github.repository}}
          github_server: ${{ github.server_url }}
          github_ref: ${{ github.ref }}

      # need to save these as artifacts so the comment-pr workflow can pick it up because
      # this action has no write access to pull requests (even adding comments)
      - name: Save PR number and scan results
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.number }} > ./pr/NR
          ./build/secops_report.sh trufflehog_report.json > ./pr/PRBODY

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/

      - name: Human readable scan report
        if: always()
        run: ./build/secops_report.sh trufflehog_report.json

      - name: Generate HTML report only if secrets were found
        if: failure()
        run: trufflehog3 -R trufflehog_report.json --output trufflehog_report.html

      - name: Upload HTML report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Security Scan Report
          path: trufflehog_report.html
          retention-days: 7
